FROM golang:1.17.7-alpine

RUN apk update &&  apk add git

WORKDIR /app
ADD ./backend /app

RUN go mod tidy && \
    go install github.com/cosmtrek/air@v1.27.3

# air -c [tomlファイル名] // 設定ファイルを指定してair実行(WORKDIRに.air.tomlを配置しておくこと)
CMD ["air", "-c", ".air.toml"]
